server:
  port: 7001
  
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/wanlichao/XH-ServerConfig
          searchPaths:  config-repo
          username: wanlc@91xunhui.com 
          password: password
      
logging:
  config: file:config/logback.xml
