zuul:
  routes:
    book:
      path: /books/**
      url: http://localhost:2222
    animal:
      path: /animals/**
      url: http://localhost:1111
      
ribbon:
  eureka:
    enabled: false
    
server:
  port: 8081
      
logging:
  config: file:config/logback.xml
  
token: 
  secret: 9SyECk96oDsTmXfogIieDI0cD/8FpnojlYSUJT5U9I/FGVmBz5oskmjOR8cbXTvoPjX+Pq/T/b1PqpHX0lYm0oCBjXWICA==